### ISSUE TITLE
No PI Score Calculated Using Additional Datasets

### ISSUE THREAD

**Issue by GreatDanPeng** [Tang-Lab-super/PROST#10]
Hi @Sicrve11 hope you're doing well! I'm using my SVG dataset from visium with both gene exp counts and spatial coordinates. Since my own dataset isn't initialized with the same column names like `array_row` and `array_col` as your data, I add new columns to match them by 
```
adata.obs["array_row"] = adata.obs["yaxis"].astype(int)
adata.obs["array_col"] = adata.obs["xaxis"].astype(int)
adata.obsm["spatial"] = np.array(adata.obs[["xaxis", "yaxis"]])
```
And then I ran the first tutorial code:
```
# Run PROST
adata = PROST.prepare_for_PI(adata, platform="visium")
adata = PROST.cal_PI(adata, platform="visium")

# Plot detected genes
PROST.plot_gene(adata, platform="visium", size=2, sorted_by="PI", top_n=25, save_path=output_dir)
```
I ran this calculation for over 20mins and got the plot but the PI scores are all `Nan`. Thus, I'm not sure without PI scores the SVG spatial visualization plot is still correct. And because I don't have PI scores, I can't not produce clustering either. Do you know what's wrong with calculating PI scores? Thanks!

**Comment by Sicrve11** [comment]
Hi, @GreatDanPeng  Thank you very much for your interest in our work! I see that you are having problems calculating the PI, this problem could be due to sparse data, or the coordinate conversion could cause it, but of course, the above is just a guess. Can you send me a small portion of the example data via google drive? Then I can help you better.

**Comment by GreatDanPeng** [comment]
Hi @Sicrve11 thanks for your reply! I also guess it might due to the data format where I used .csv instead of .hd. Here's the sample data I used: https://drive.google.com/drive/folders/1AA8ilR9kZWfcJ7tLTaOqUvdnbBquPc_v?usp=sharing

**Comment by Sicrve11** [comment]
Hi, @GreatDanPeng  I used the example data you gave me and I see the problem you mentioned. However, I have some questions: first of all, I need to make sure that your data is really in Visium format, because I looked at the original data based on the data number GSE144239, and the coordinates of that data are not the same as the one you gave me, and that format is neatly aligned integers. Also, I don't understand why .asype(int) is used for data processing because I saw that the coordinates of the raw data are in float format, does this mean that the data is not Visium.

So I have used the following code to do the calculation, this code is able to get the PI value result and the calculation is very fast.

```
adata = sc.read_csv("./gene_exp/GSE144239_GSM4565823_count.csv")
xy = pd.read_csv("./spatial/Visium_coord_GSE144239_GSM4565823_coord.csv", index_col=0)

adata.obs["array_row"] = xy["yaxis"]
adata.obs["array_col"] = xy["xaxis"]
adata.obsm["spatial"] = np.array(adata.obs[["array_col", "array_row"]])

adata = PROST.prepare_for_PI(adata, platform="other")
adata = PROST.cal_PI(adata, platform="other")

            n_cells       SEP       SIG        PI
NOC2L           284  0.552202  0.016191  0.188669
PLEKHN1         151  0.335654  0.008232  0.100687
HES4             85  0.365714 -0.014341  0.050327
ISG15           535  0.566629  0.021527  0.213893
AGRN            391  0.543027  0.055983  0.333623
...             ...       ...       ...       ...
MT-ND4          700  0.396353  0.066033  0.277747
MT-ND5          559  0.324378  0.037823  0.166439
MT-ND6           78  0.475242 -0.002736  0.102011
MT-CYB          689  0.413824  0.057171  0.263210
AC007325.4      101  0.529720  0.004368  0.138581

[8708 rows x 4 columns]

**Comment by GreatDanPeng** [comment]
Hi @Sicrve11 Thanks for your help and it solved this issue! You're right, the original visium data should be integer type. Since I scaled my data beforehand, the spatial data is float type. Thanks for letting me know the parameter platform="other". In this case the data might not fit to "visium", where using "other" can be a better choice.
