### ISSUE TITLE
Installation bug report on Linux Ubuntu

### ISSUE THREAD

**Issue by rocketeer1998** [Tang-Lab-super/PROST#6]
Hi @Sicrve11 , thanks again for your contribution to this great tool! I've been working around installing PROST on my Linux machine but failed on `pip install -r requirements.txt` following your documents' instruction. Specifically, rpy2 was not able to be built as the error said `Failed building wheel for rpy2`. Inspired by the solution in [here](https://stackoverflow.com/questions/48352018/install-rpy2-returns-an-error) and I can successfully install PROST now. Hope this workaround can help you improve PROST further.

**Comment by Sicrve11** [comment]
Thanks again for your feedback! `rpy2` is indeed a hard package, it's more strict on the environmental requirements. We tested it only using `conda` under the Centos or the Windows. You have provided another solution, thank you very much!

**Comment by GreatDanPeng** [comment]
Thanks for your @rocketeer1998 suggestions! Unfortunately, since I don't have **sudo permission** in my longleaf server, and I couldn't install rpy2 with the following error:
```
fatal error: crypt.h: No such file or directory
     44 | #include <crypt.h>
        |          ^~~~~~~~~
  compilation terminated.
  error: command '/miniconda3/envs/PROST_ENV/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for rpy2
Failed to build rpy2
```
### Solution
Because the crypt.h file is typically provided by the libxcrypt development package. I solved this error by checking the required lib first and making sure `libxcrypt-devel.x86_64` is installed.
```
yum list installed | grep libxcrypt
```
Then, specify paths to existing libraries by locating `crypt.h`:
```
find /usr -name crypt.h 2>/dev/null
```
After running this command, you may get path like `/usr/include/crypt.h`. Thus, add the directory containing the correct `crypt.h` to the `CFLAGS` environment variable:
```
export CFLAGS="-I/usr/include"
```
Now, run `pip install rpy2==2.9.4` as requirement.txt mentions and it's good to go.
